{% set name = "fluidsim" %}
{% set version = "0.4.1" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: afc33a656fdbbd0977c253480a9125616a719f04bddbf7f902b10e6744d3d3c8

build:
  number: {{ build }}
  entry_points:
    - fluidsim = fluidsim.util.console.__main__:run
    - fluidsim-bench = fluidsim.util.console.__main__:run_bench
    - fluidsim-bench-analysis = fluidsim.util.console.__main__:run_bench_analysis
    - fluidsim-create-xml-description = fluidsim.base.output:run
    - fluidsim-profile = fluidsim.util.console.__main__:run_profile
    - fluidsim-test = fluidsim.util.testing:run
  skip: true  # [win or py<36]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - transonic
    - setuptools_scm
    - pythran
  run:
    - python
    - fluidsim-core
    - fluidfft
    - numpy >=1.15.4
    - cached-property
    - setuptools_scm
    - xarray
    - pandas
    - transonic

test:
  imports:
    - fluidsim
  commands:
    - fluidsim-test -v  # [not osx]

about:
  home: https://foss.heptapod.net/fluiddyn/fluidsim
  license: LicenseRef-CeCILL
  license_file: LICENSE.txt
  summary: Framework for studying fluid dynamics with simulations.
  description: |
    Fluidsim is an extensible framework for studying fluid dynamics with
    numerical simulations using Python. Fluidsim is an object-oriented library
    to develop solvers (mainly using pseudo-spectral methods) by writing mainly
    Python code. The result is very efficient even compared to a pure Fortran or
    C++ code since the time-consuming tasks are performed by optimized compiled
    functions.
  doc_url: https://fluidsim.readthedocs.io

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
