{% set name = "fluidsim" %}
{% set version = "0.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0cc50d969284abf26541ace3e3e328824cd3ba980d699748c4b043cbe9f29d09

build:
  number: 0
  entry_points:
    - fluidsim = fluidsim.util.console.__main__:run
    - fluidsim-bench = fluidsim.util.console.__main__:run_bench
    - fluidsim-bench-analysis = fluidsim.util.console.__main__:run_bench_analysis
    - fluidsim-create-xml-description = fluidsim.base.output:run
    - fluidsim-profile = fluidsim.util.console.__main__:run_profile
    - fluidsim-test = fluidsim.util.testing:run
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - ninja                                  # [unix]
    - pkg-config                             # [unix]
    # pythran code needs clang-cl on windows
    - clang                                  # [win]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - python-build
    - pip
    - meson-python
    - numpy
    - transonic >=0.6.4
    - pythran >=0.9.7
  run:
    - python
    - ipython
    - transonic >=0.6.4
    - fluidsim-core >=0.8.0
    - fluidfft >=0.4.0
    - numpy >=1.15.4
    - matplotlib-base
    - pandas
    - xarray
    - pytest
    - rich
    - importlib-metadata

test:
  requires:
    - pip
  imports:
    - fluidsim
    # manual imports of few important Pythran extensions
    - fluidsim.base.output.__pythran__.increments
    - fluidsim.base.output.__pythran__.spatiotemporal_spectra
    # A dynamic link library (DLL) initialization routine failed.
    - fluidsim.base.time_stepping.__pythran__.pseudo_spect  # [not win]
    - fluidsim.operators.__pythran__.operators2d
    - fluidsim.operators.__pythran__.operators3d
    - fluidsim.solvers.ns2d.__pythran__.solver
    - fluidsim.solvers.ns2d.bouss.__pythran__.solver
    - fluidsim.solvers.ns2d.output.__pythran__.spatiotemporal_spectra
    - fluidsim.solvers.ns2d.strat.__pythran__.solver
    - fluidsim.solvers.ns3d.forcing.__pythran__.watu
    - fluidsim.solvers.ns3d.output.__pythran__.spatiotemporal_spectra
    - fluidsim.solvers.ns3d.strat.__pythran__.solver
    - fluidsim.solvers.plate2d.__pythran__.operators
    - fluidsim.solvers.plate2d.output.__pythran__.correlations_freq
    - fluidsim.solvers.sphere.sw1l.__pythran__.solver
    - fluidsim.solvers.sw1l.__pythran__.operators
    - fluidsim.solvers.sw1l.__pythran__.solver
    - fluidsim.solvers.sw1l.output.__pythran__.base
    - fluidsim.util.__pythran__.mini_oper_modif_resol
  # TODO: retry when https://foss.heptapod.net/fluiddyn/fluidsim/-/issues/157 is fixed
  # commands:
  #   - python -m pip install pytest-allclose pytest-mock
  #   - fluidsim-test -v

about:
  home: https://foss.heptapod.net/fluiddyn/fluidsim
  license: LicenseRef-CeCILL
  license_file: LICENSE.txt
  summary: Framework for studying fluid dynamics with simulations.
  description: |
    Fluidsim is an extensible framework for studying fluid dynamics with
    numerical simulations using Python. Fluidsim is an object-oriented library
    to develop solvers (mainly using pseudo-spectral methods) by writing mainly
    Python code. The result is very efficient even compared to a pure Fortran or
    C++ code since the time-consuming tasks are performed by optimized compiled
    functions.
  doc_url: https://fluidsim.readthedocs.io

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
    - ashwinvis
