{% set name = "fluidsim" %}
{% set version = "0.8.1" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 44c70f388c429856f5df24705cddb2e024d7d1376d2153e113ef111af90b857b

build:
  number: {{ build }}
  entry_points:
    - fluidsim = fluidsim.util.console.__main__:run
    - fluidsim-bench = fluidsim.util.console.__main__:run_bench
    - fluidsim-bench-analysis = fluidsim.util.console.__main__:run_bench_analysis
    - fluidsim-create-xml-description = fluidsim.base.output:run
    - fluidsim-profile = fluidsim.util.console.__main__:run_profile
    - fluidsim-test = fluidsim.util.testing:run
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - meson-python
    - numpy
    - transonic >=0.6.1
    - pythran >=0.9.7
    # pythran code needs clang-cl on windows
    - clang  # [win]
  run:
    - python
    - ipython
    - transonic >=0.6.1
    - fluidsim-core >=0.8.0
    - fluidfft >=0.4.0
    - numpy >=1.15.4
    - matplotlib-base
    - pandas
    - xarray
    - pytest
    - rich
    - importlib_metadata
    # - cached-property

test:
  requires:
    - pip
  imports:
    - fluidsim
  # TODO: try to uncomment for 0.8.1
  # commands:
  #   - python -m pip install pytest-allclose pytest-mock
  #   - fluidsim-test -v

about:
  home: https://foss.heptapod.net/fluiddyn/fluidsim
  license: LicenseRef-CeCILL
  license_file: LICENSE.txt
  summary: Framework for studying fluid dynamics with simulations.
  description: |
    Fluidsim is an extensible framework for studying fluid dynamics with
    numerical simulations using Python. Fluidsim is an object-oriented library
    to develop solvers (mainly using pseudo-spectral methods) by writing mainly
    Python code. The result is very efficient even compared to a pure Fortran or
    C++ code since the time-consuming tasks are performed by optimized compiled
    functions.
  doc_url: https://fluidsim.readthedocs.io

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
    - ashwinvis
