{% set name = "fluidsim" %}
{% set version = "0.6.1" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 619b94dbae322996929921c82545bfc561c3403eeabaafcafd74b3e8b29a7210

build:
  number: {{ build }}
  entry_points:
    - fluidsim = fluidsim.util.console.__main__:run
    - fluidsim-bench = fluidsim.util.console.__main__:run_bench
    - fluidsim-bench-analysis = fluidsim.util.console.__main__:run_bench_analysis
    - fluidsim-create-xml-description = fluidsim.base.output:run
    - fluidsim-profile = fluidsim.util.console.__main__:run_profile
    - fluidsim-test = fluidsim.util.testing:run
  skip: true  # [py<38 or (win and py==310)]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - transonic
    - setuptools_scm
    - pythran
  run:
    - python
    - fluidsim-core >=0.6.1rc1
    - fluidfft
    - numpy >=1.15.4
    - cached-property
    - setuptools_scm
    - xarray
    - pandas
    - transonic
    - pytest
    - rich

test:
  requires:
    - pip
  imports:
    - fluidsim
  commands:
    - python -m pip install pytest-allclose
    - fluidsim-test -v

about:
  home: https://foss.heptapod.net/fluiddyn/fluidsim
  license: LicenseRef-CeCILL
  license_file: LICENSE.txt
  summary: Framework for studying fluid dynamics with simulations.
  description: |
    Fluidsim is an extensible framework for studying fluid dynamics with
    numerical simulations using Python. Fluidsim is an object-oriented library
    to develop solvers (mainly using pseudo-spectral methods) by writing mainly
    Python code. The result is very efficient even compared to a pure Fortran or
    C++ code since the time-consuming tasks are performed by optimized compiled
    functions.
  doc_url: https://fluidsim.readthedocs.io

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
    - ashwinvis
